var tags = {
  britain: ["Little Waltham", "Walkley", "Marchington", "Sutton-cum-Lound", "Mucking", "Sedlescombe", "Luton", "Crowle", "Bobbingworth", "Lawford Heath", "Fyfield", "Rampton", "Lullington", "Thorpe-le-Soken", "Whiston", "Harwood", "Hathern", "Church Brampton", "Warkworth", "Stamford", "Notton", "Rhyl", "Ripley", "Billingley", "Thurrock", "Allendale", "Netherseale", "Broomfield", "Fryerning", "Bamborough", "Potterhanworth", "Sutton", "Bedford", "Norwich", "Westminster", "Ingatestone", "Rossendale", "Great Creaton", "Warsop", "Bacup", "Thorne", "Levington", "Ottershaw", "Bredons Norton", "Llantwit Major", "Great Comberton", "Grove", "Overbury", "Church Lawford", "Whichford", "Lurgashall", "South Runcton", "Sculthorpe", "Pabbay (North)", "Wendens Ambo", "Saxthorpe", "Winfarthing", "Scottow", "Sheering", "Elton", "Chilcompton", "Rodmersham", "Harrington", "Hayton", "Wherstead", "Chelmondiston", "Alnwick", "Winchester", "Marwood", "Buriton", "Stifford", "Cwmbran", "Stanground", "Pathfinder Village", "Teynham", "Aslockton", "Euston", "Dunkerton", "Etwall", "Kirby Knowle", "Reverse Kirby Knowle", "Bar Point", "Wistow", "Reverse Sutton", "Dorrington", "Didcot", "Vowchurch", "Great Badminton", "Eastleach Martin", "Oxford", "Reverse Oxford", "Llanarthne", "Llanarthne II", "Badbury", "Reverse Finchampstead", "Finchampstead", "Stanton", "Reverse Stanton", "Egloskerry", "Ayston", "Tinwell", "Reverse Tinwell", "Lyndon", "Ridlington", "Southrise", "Coln Valley", "Barton", "Melsonby", "East Layton", "Cherington", "Stanway", "Wyck Rissington", "Elmstone Hardwicke", "Daglingworth", "Clearwell", "Canterbury", "Reverse Canterbury", "Double Canterbury", "Reverse Adbaston", "Reverse Allexton", "Reverse Ayston", "Reverse Barkeston", "Reverse Bobbington", "Reverse Burrough-on-the-Hill", "Reverse Chebsey", "Reverse Colton", "Reverse Cubley", "Reverse Dalby-on-the-Wolds", "Reverse Denstone", "Reverse Drayton Bassett", "Reverse Elvaston"],
  river: ["Mersey", "Wearmouth"],
  saint: ["St Peter", "San Pietro", "St Ippolyts", "St Hybald", "St Remigius", "Reverse St Remigius", "St Alphege", "St Aelhaiarn", "St Nicholas", "Reverse St Nicholas"],
  mountain: ["An Teallach", "Sgurr Mor", "Scafell Pike", "Brandon Mountain", "Beinn Bhan", "Carnedd Llewelyn", "Sgurr na Lapaich", "Broad Law", "Beinn Fhada"],
  name: ["Charles", "Marguerite", "Erin", "Reverse Erin", "Carter", "Reverse Carter", "Ermin"],
  person: ["Edith Weston", "Nanny Piggins", "Holmes", "Stedman", "Reverse Stedman", "Geraint Thomas"],
  estate: ["Luton Hoo", "Lindisfarne", "Pitsligo Castle"],
  adjective: ["Royal Bob", "Unacceptable", "New Superlative", "Civic", "Steep", "Original", "Titanic", "Reverse Original", "Reverse Titanic", "Rustic", "Rural", "Cheeky", "Plain", "Double", "Reverse", "Dusty"],
  germany: ["Witten"],
  object: ["Carpet Cleaner"],
  lake: ["Loch Garve"],
  "person's thing": ["Geoffrey Dodd's Tulipish", "Mr Wood's Double"],
  animal: ["Cuckoo", "Reverse Chipmunk"],
  sentence: ["A Small Cure for Melancholy", "In These Unprecedented And Challenging Times Our First Priority Is The Safety Of Our Staff"],
  place: ["Churchyard", "Reverse Churchyard", "Coastal Stations", "Inshore Waters", "Court", "Reverse Court", "Single Court", "Double Court", "Countryside"],
  religion: ["The God", "Trinity", "Te Deum"],
  unknown: ["Bifter", "Culfrey", "Plain Octets", "Compton Peculiar No.3", "General Synopsis", "Ten Rides", "Small Blue Cupido", "Itram", "Fosse", "Bastow", "Wader Wodon", "Ypsen Harpen", "Lathors Cure", "Smod Hole Inn", "Reverse Carlton-by-Bosworth"],
  book: ["Trilogy"],
  statue: ["Aldworth Giants'"],
  character: ["Double Dracula"],
  medicine: ["Cardiac Arrest"],
  benefice: ["Avon-Swift", "Churn Valley"],
  australia: ["Rous Hotel"],
  weather: ["Morning Fog", "Shipping Forecast"],
  military: ["41st Battalion"],
  shape: ["Cross"],
  job: ["Boatman's", "New Boatman's"],
  number: ["Sixty"],
  concept: ["Double Trouble"],
  herb: ["Parsley", "Rosemary", "Sage", "Thyme"],
  food: ["Rhubarb", "Custard", "Reverse Burrito", "Reverse Chimichanga", "Reverse Enchilada", "Reverse Flauta"]
};

var last = "Reverse Flauta Alliance Minimus";